# Site Settings
title: A ross blog
email: rossbernet@gmail.com
description: >
  A blog about and by and for ross
baseurl: ""
url: "http://localhost:4000"
twitter_username: rossbernet
github_username:  rosszb
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM